import { Libre_Baskerville } from "next/font/google";
import "./globals.css";

const libre_bask = Libre_Baskerville({
  subsets: ['latin'],
  display: 'swap',
  weight : '400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${libre_bask.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
